### ISSUE TITLE
后台评论管理登录不上

### ISSUE THREAD

**Issue by AlliotTech** [panjunwen/Valine-Admin#12]
更新后  后台管理登录没有反应。 在user表中邮件重置了密码也不能登录 。

**Comment by panjunwen** [comment]
由于合并了kfangf的PR，最新版须使用邮箱登录（出于安全考虑，虽然我觉得这么做没卵用😄）。且数据库中设置的管理员邮箱要和环境变量中的BLOGGER_MAIL或SENDER_MAIL一致。

**Comment by AlliotTech** [comment]
emmm  已经尝试过了。。。 依旧没反应。。是不是BLOGGER_EMAIL与SENDER_MAIL都得一致。。。。 我俩个不一样 。。。

**Comment by panjunwen** [comment]
只需和BLOOGER_MAIL一致即可

**Comment by AlliotTech** [comment]
已解决。。需要重新再user中验证邮箱，重启实列。
