### ISSUE TITLE
跳转到对应评论的bug

### ISSUE THREAD

**Issue by redstoneleo** [panjunwen/Valine-Admin#13]
邮件通知里的链接可以设置了跳转到对应评论，但是当跳转到对应页面的时候，评论框及其内容是没有加载出来的，所以无法跳转到对应的评论。

是不是可以等评论框及其内容加载完成后再次跳转到对应评论？

**Comment by panjunwen** [comment]
请仔细阅读说明文档，详见https://panjunwen.com/valine-admin-document/。

点击邮件中的链接跳转至相应评论，这一细节实现需要一点额外的代码（添加到Valine所在的页面）：

<script>
    if(window.location.hash){
        var checkExist = setInterval(function() {
           if ($(window.location.hash).length) {
              $('html, body').animate({scrollTop: $(window.location.hash).offset().top-90}, 1000);
              clearInterval(checkExist);
           }
        }, 100);
    }
</script>

**Comment by redstoneleo** [comment]
帅了，谢谢老铁！！！
