### ISSUE TITLE
建议邮件回复模板里增加  POST_TITLE

### ISSUE THREAD

**Issue by redstoneleo** [panjunwen/Valine-Admin#14]
希望增加一个POST_TITLE，可以取document.title, 网站的名字游客可能记不住，但是评论过的帖子的名称游客会记忆更深刻一点，然后我们把POST_TITLE放到通知邮件的标题里去，游客收到邮件提醒就不会感到陌生了，这样子体验会更好。

**Comment by panjunwen** [comment]
这是后端，想加自己加吧

**Comment by redstoneleo** [comment]
我是想着可以在评论系统里实现这个功能。
自己加的话估计又要重新请求网页获取数据才行，不是太方便
