### ISSUE TITLE
后台管理登录的用户名密码需要在数据库_User表中自行添加

### ISSUE THREAD

**Issue by tiexo** [panjunwen/Valine-Admin#15]
这一步能不能详细点呀....没弄懂怎么添加。

**Comment by panjunwen** [comment]
已经解决，请部署新版并访问https://二级域名/sign-up

**Comment by msdx** [comment]
@DesertsP 我访问了该地址，但是未完成注册时关掉了，之后再打开该地址会重定向到登录页面，但我并不知道我自己的密码（由于前一步没有去设置），导致无法登录。
