### ISSUE TITLE
无法设置管理员登录信息

### ISSUE THREAD

**Issue by xlui** [panjunwen/Valine-Admin#17]
访问 `xxx.leanapp.cn/sign-up` 直接 302 重定向到 `xxx.leanapp.cn/`

**Comment by panjunwen** [comment]
出于安全考虑，_USER表内如果已经存在管理员邮箱关联的账户，将禁止再次配置。
请自行删除_USER表中的相关信息。

一种典型的情形是，使用了原版的VALINE并开启了邮件通知，这种情况下直接清空USER表即可。

**Comment by xlui** [comment]
了解，问题已解决
