### ISSUE TITLE
可能不需要部署

### ISSUE THREAD

**Issue by fengbjhqs** [panjunwen/Valine-Admin#7]
您好，

leancloud是支持跨域，可以使用Master Key，

所以如果只是管理评论，是不是可以不需要部署，

可以使用静态页面即可

**Comment by panjunwen** [comment]
是的。但是部署有诸多好处。
一是用来实现邮件通知等功能，二是避免使用Master Key。还可以用这个部署的网站达到唤醒休眠的效果。何乐而不为！

**Comment by panjunwen** [comment]
是的。但是部署有诸多好处。
一是用来实现邮件通知等功能，二是避免使用Master Key。还可以用这个部署的网站达到唤醒休眠的效果。何乐而不为！
