### ISSUE TITLE
邮件无效，垃圾评论不自动处理

### ISSUE THREAD

**Issue by AlliotTech** [panjunwen/Valine-Admin#9]
垃圾评论只进行标记  不进行删除操作吗？
另外 网易邮箱做发件邮箱，无效。配置如下
![image](https://user-images.githubusercontent.com/24980252/46475758-ffbac280-c818-11e8-8a02-4172992fdf7a.png)
感谢owner的项目~

**Comment by panjunwen** [comment]
邮箱问题马上修复，请稍等

**Comment by AlliotTech** [comment]
感谢 修补。
垃圾评论的问题是本身就没有做处理还是我这边异常了呢？

**Comment by panjunwen** [comment]
你好，邮件问题已经修复，烦请新增以下环境变量，并在Leancloud云引擎部署页再次点击部署即可更新到最新版本。
`SMTP_SERVICE`，值为```163```，更多支持邮箱请查阅https://nodemailer.com/smtp/well-known/#supported-services

原 SMTP_HOST，SMTP_PORT 两个变量在设定 SMTP_SERVICE 后失效。
（感谢ZhaoJun及Nodemailer）

垃圾评论检测只会将`Spam`字段标记为`true`，不会删除相关数据。原版Valine不支持垃圾评论过滤，仍会把垃圾评论显示在前端。你可以使用[我提供的Valine](https://github.com/panjunwen/Valine)或者自行修改原版使其适配垃圾评论过滤功能。
